### PR TITLE
Change file names

### PR DESCRIPTION
**Pull request by magistau**
New file names are easier to type
Also added some symlinks

### CODE REVIEW

**Comment by subnut** [comment]
Please remove all the NDC themes, and squash the commits and then force-push

```
rm *ndc.tmTheme
git reset --soft 9d5153d88
git commit -m "Rename files, remove NDC themes, add symlinks"
git push --force
```

**Comment by magistau** [comment]
> Please remove all the NDC themes, and squash the commits and then force-push
> 
> ```
> rm *ndc.tmTheme
> git reset --soft 9d5153d88
> git commit -m "Rename files, remove NDC themes, add symlinks"
> git push --force
> ```

I know how to do that, but why do you not want ndc's?

**Comment by magistau** [comment]
Oh read the comment in bat repo

**Comment by subnut** [comment]
Hey @j0hnmeow, wouldn't it simply complicate the end-user even more when there is a `gruvbox`, a `gruvbox-dark`, etc..
I think the extra (symlink) themes weren't nessecary, only the original (variants) should remain..

Otherwise it will cause ambiguity

**Comment by subnut** [comment]
i.e. only the original (variants) should remain,

**Comment by subnut** [comment]
Sorry for the hiccup....

**Comment by magistau** [comment]
So you don't like the idea of shortcuts?

**Comment by subnut** [comment]
No no, not shortcuts...... you misunderstood me

See.. when the user runs `bat --preview`, the output shows duplicate themes (e.g. `gruvbox` is exactly the same as `gruvbox-dark`, which in turn is same as `gruvbox-dark-medium`)
This may cause confusion right?

**Comment by magistau** [comment]
Yeah. Maybe `bat` should be able to recognize symlinks and show them differently

**Comment by subnut** [comment]
Yep!
But till that happens, won't it be better to not keep the symlinks?

**Comment by subnut** [comment]
Or are you going to fix `bat` itself? :wink:

**Comment by subnut** [comment]
> till that happens, won't it be better to not keep the symlinks?

@j0hnmeow Waiting for your opinion

**Comment by magistau** [comment]
> Or are you going to fix `bat` itself? :wink:

I am

**Comment by magistau** [comment]
> > till that happens, won't it be better to not keep the symlinks?
> 
> @j0hnmeow Waiting for your opinion

Removed the symlinks
smh it is already merged so it's not possible to merge it again? Should I create a new PR?

**Comment by subnut** [comment]
> Should I create a new PR?

I think so, since there is no other method AFAIK

**Comment by magistau** [comment]
#2

**Comment by subnut** [comment]
Just for future reference, this PR was originally merged into the `main` branch, but that branch has since been renamed to `bat-source`

All new PRs related to `bat` shall now be directed towards the `bat-source` branch, and the `main` branch shall be kept for the original files taken from Briles/gruvbox@ec4eae2

**Pull request merged**
