### PR TITLE
No symlinks

### PR DESCRIPTION
**Pull request by magistau**
Continuation of #1

### CODE REVIEW

**Comment by magistau** [comment]
~~This could be my 8th hacktoberfest PR~~

**Comment by subnut** [comment]
@j0hnmeow  Well I added the `hacktoberfest` label to this repo, so is this PR going to be considered?

**Comment by magistau** [comment]
Both are. Ty

**Comment by subnut** [comment]
Just for future reference, this PR was originally merged into the `main` branch, but that branch has since been renamed to `bat-source`

All new PRs related to `bat` shall now be directed towards the `bat-source` branch, and the `main` branch shall be kept for the original files taken from Briles/gruvbox@ec4eae2

**Pull request merged**
